# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_long',
            field=models.TextField(),
        ),
    ]
