# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160123_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 23, 20, 8, 25, 894810, tzinfo=utc), verbose_name='ending date'),
            preserve_default=False,
        ),
    ]
